# Generated by Django 5.0.6 on 2024-06-24 23:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=api.models.upload_to)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
