# Generated by Django 5.0.6 on 2024-06-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('ImageId', models.AutoField(primary_key=True, serialize=False)),
                ('ImageName', models.CharField(max_length=100)),
                ('ImageFile', models.CharField(max_length=100)),
            ],
        ),
    ]
